before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-log-dev libprotobuf-dev protobuf-compiler libzmq3-dev xsdcxx
 - autoreconf
language: cpp
compiler:
  - gcc
script: 
  - ./configure --enable-precompiled-protocols=no --enable-silent-rules
  - make
