before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libprotobuf-dev libzmq3-dev
language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./configure --enable-precompiled-protocols && make
