before_install:
 - sudo add-apt-repository ppa:boost-latest/ppa -y
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8 libboost-log1.55-dev libprotobuf-dev protobuf-compiler libzmq3-dev xsdcxx
 - autoreconf
language: cpp
compiler:
  - gcc
script: 
  - export CXX="g++-4.8"
  - ./configure --enable-precompiled-protocols=no --enable-silent-rules
  - make
