before_install:
 - sudo apt-get update
 - sudo apt-get install libprotobuf-dev libzmq3-dev
 - autoreconf
language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./configure --enable-precompiled-protocols && make
