before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libprotobuf-dev libzmq3-dev xsdcxx
 - autoreconf
language: cpp
compiler:
  - gcc
script: 
  - ./configure --enable-precompiled-protocols=yes --enable-silent-rules
  - make
