// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocols.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protocols.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ABT_CommunicationProtocol_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_CommunicationProtocol_reflection_ = NULL;
const ::google::protobuf::Descriptor* ABT_CommunicationProtocol_AgentIdentity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_CommunicationProtocol_AgentIdentity_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ABT_CommunicationProtocol_MessageType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* ABT_Assignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_Assignment_reflection_ = NULL;
const ::google::protobuf::Descriptor* ABT_CompoundAssignment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_CompoundAssignment_reflection_ = NULL;
const ::google::protobuf::Descriptor* ABT_Message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_Message_reflection_ = NULL;
const ::google::protobuf::Descriptor* ABT_Message_OK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_Message_OK_reflection_ = NULL;
const ::google::protobuf::Descriptor* ABT_Message_NOGOOD_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ABT_Message_NOGOOD_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ABT_Message_MessageType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_protocols_2eproto() {
  protobuf_AddDesc_protocols_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protocols.proto");
  GOOGLE_CHECK(file != NULL);
  ABT_CommunicationProtocol_descriptor_ = file->message_type(0);
  static const int ABT_CommunicationProtocol_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol, identity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol, others_),
  };
  ABT_CommunicationProtocol_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_CommunicationProtocol_descriptor_,
      ABT_CommunicationProtocol::default_instance_,
      ABT_CommunicationProtocol_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_CommunicationProtocol));
  ABT_CommunicationProtocol_AgentIdentity_descriptor_ = ABT_CommunicationProtocol_descriptor_->nested_type(0);
  static const int ABT_CommunicationProtocol_AgentIdentity_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol_AgentIdentity, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol_AgentIdentity, host_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol_AgentIdentity, port_),
  };
  ABT_CommunicationProtocol_AgentIdentity_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_CommunicationProtocol_AgentIdentity_descriptor_,
      ABT_CommunicationProtocol_AgentIdentity::default_instance_,
      ABT_CommunicationProtocol_AgentIdentity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol_AgentIdentity, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CommunicationProtocol_AgentIdentity, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_CommunicationProtocol_AgentIdentity));
  ABT_CommunicationProtocol_MessageType_descriptor_ = ABT_CommunicationProtocol_descriptor_->enum_type(0);
  ABT_Assignment_descriptor_ = file->message_type(1);
  static const int ABT_Assignment_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Assignment, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Assignment, value_),
  };
  ABT_Assignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_Assignment_descriptor_,
      ABT_Assignment::default_instance_,
      ABT_Assignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Assignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Assignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_Assignment));
  ABT_CompoundAssignment_descriptor_ = file->message_type(2);
  static const int ABT_CompoundAssignment_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CompoundAssignment, assignments_),
  };
  ABT_CompoundAssignment_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_CompoundAssignment_descriptor_,
      ABT_CompoundAssignment::default_instance_,
      ABT_CompoundAssignment_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CompoundAssignment, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_CompoundAssignment, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_CompoundAssignment));
  ABT_Message_descriptor_ = file->message_type(3);
  static const int ABT_Message_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message, ok_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message, nogood_data_),
  };
  ABT_Message_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_Message_descriptor_,
      ABT_Message::default_instance_,
      ABT_Message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_Message));
  ABT_Message_OK_descriptor_ = ABT_Message_descriptor_->nested_type(0);
  static const int ABT_Message_OK_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message_OK, assignment_),
  };
  ABT_Message_OK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_Message_OK_descriptor_,
      ABT_Message_OK::default_instance_,
      ABT_Message_OK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message_OK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message_OK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_Message_OK));
  ABT_Message_NOGOOD_descriptor_ = ABT_Message_descriptor_->nested_type(1);
  static const int ABT_Message_NOGOOD_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message_NOGOOD, nogood_),
  };
  ABT_Message_NOGOOD_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ABT_Message_NOGOOD_descriptor_,
      ABT_Message_NOGOOD::default_instance_,
      ABT_Message_NOGOOD_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message_NOGOOD, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ABT_Message_NOGOOD, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ABT_Message_NOGOOD));
  ABT_Message_MessageType_descriptor_ = ABT_Message_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protocols_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_CommunicationProtocol_descriptor_, &ABT_CommunicationProtocol::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_CommunicationProtocol_AgentIdentity_descriptor_, &ABT_CommunicationProtocol_AgentIdentity::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_Assignment_descriptor_, &ABT_Assignment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_CompoundAssignment_descriptor_, &ABT_CompoundAssignment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_Message_descriptor_, &ABT_Message::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_Message_OK_descriptor_, &ABT_Message_OK::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ABT_Message_NOGOOD_descriptor_, &ABT_Message_NOGOOD::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protocols_2eproto() {
  delete ABT_CommunicationProtocol::default_instance_;
  delete ABT_CommunicationProtocol_reflection_;
  delete ABT_CommunicationProtocol_AgentIdentity::default_instance_;
  delete ABT_CommunicationProtocol_AgentIdentity_reflection_;
  delete ABT_Assignment::default_instance_;
  delete ABT_Assignment_reflection_;
  delete ABT_CompoundAssignment::default_instance_;
  delete ABT_CompoundAssignment_reflection_;
  delete ABT_Message::default_instance_;
  delete ABT_Message_reflection_;
  delete ABT_Message_OK::default_instance_;
  delete ABT_Message_OK_reflection_;
  delete ABT_Message_NOGOOD::default_instance_;
  delete ABT_Message_NOGOOD_reflection_;
}

void protobuf_AddDesc_protocols_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017protocols.proto\"\306\002\n\031ABT_CommunicationP"
    "rotocol\0224\n\004type\030\001 \002(\0162&.ABT_Communicatio"
    "nProtocol.MessageType\022:\n\010identity\030\002 \001(\0132"
    "(.ABT_CommunicationProtocol.AgentIdentit"
    "y\0228\n\006others\030\003 \003(\0132(.ABT_CommunicationPro"
    "tocol.AgentIdentity\0327\n\rAgentIdentity\022\n\n\002"
    "id\030\001 \002(\005\022\014\n\004host\030\002 \002(\t\022\014\n\004port\030\003 \002(\005\"D\n\013"
    "MessageType\022\017\n\013T_INTRODUCE\020\001\022\016\n\nT_GET_LI"
    "ST\020\002\022\t\n\005T_BYE\020\003\022\t\n\005T_ACK\020\004\"+\n\016ABT_Assign"
    "ment\022\n\n\002id\030\001 \002(\005\022\r\n\005value\030\002 \002(\005\">\n\026ABT_C"
    "ompoundAssignment\022$\n\013assignments\030\001 \003(\0132\017"
    ".ABT_Assignment\"\255\002\n\013ABT_Message\022&\n\004type\030"
    "\001 \002(\0162\030.ABT_Message.MessageType\022\n\n\002id\030\002 "
    "\002(\005\022 \n\007ok_data\030\003 \001(\0132\017.ABT_Message.OK\022(\n"
    "\013nogood_data\030\004 \001(\0132\023.ABT_Message.NOGOOD\032"
    ")\n\002OK\022#\n\nassignment\030\001 \002(\0132\017.ABT_Assignme"
    "nt\0321\n\006NOGOOD\022\'\n\006nogood\030\001 \002(\0132\027.ABT_Compo"
    "undAssignment\"@\n\013MessageType\022\010\n\004T_OK\020\001\022\014"
    "\n\010T_NOGOOD\020\002\022\r\n\tT_ADDLINK\020\003\022\n\n\006T_STOP\020\004", 759);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protocols.proto", &protobuf_RegisterTypes);
  ABT_CommunicationProtocol::default_instance_ = new ABT_CommunicationProtocol();
  ABT_CommunicationProtocol_AgentIdentity::default_instance_ = new ABT_CommunicationProtocol_AgentIdentity();
  ABT_Assignment::default_instance_ = new ABT_Assignment();
  ABT_CompoundAssignment::default_instance_ = new ABT_CompoundAssignment();
  ABT_Message::default_instance_ = new ABT_Message();
  ABT_Message_OK::default_instance_ = new ABT_Message_OK();
  ABT_Message_NOGOOD::default_instance_ = new ABT_Message_NOGOOD();
  ABT_CommunicationProtocol::default_instance_->InitAsDefaultInstance();
  ABT_CommunicationProtocol_AgentIdentity::default_instance_->InitAsDefaultInstance();
  ABT_Assignment::default_instance_->InitAsDefaultInstance();
  ABT_CompoundAssignment::default_instance_->InitAsDefaultInstance();
  ABT_Message::default_instance_->InitAsDefaultInstance();
  ABT_Message_OK::default_instance_->InitAsDefaultInstance();
  ABT_Message_NOGOOD::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protocols_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protocols_2eproto {
  StaticDescriptorInitializer_protocols_2eproto() {
    protobuf_AddDesc_protocols_2eproto();
  }
} static_descriptor_initializer_protocols_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ABT_CommunicationProtocol_MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_CommunicationProtocol_MessageType_descriptor_;
}
bool ABT_CommunicationProtocol_MessageType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ABT_CommunicationProtocol_MessageType ABT_CommunicationProtocol::T_INTRODUCE;
const ABT_CommunicationProtocol_MessageType ABT_CommunicationProtocol::T_GET_LIST;
const ABT_CommunicationProtocol_MessageType ABT_CommunicationProtocol::T_BYE;
const ABT_CommunicationProtocol_MessageType ABT_CommunicationProtocol::T_ACK;
const ABT_CommunicationProtocol_MessageType ABT_CommunicationProtocol::MessageType_MIN;
const ABT_CommunicationProtocol_MessageType ABT_CommunicationProtocol::MessageType_MAX;
const int ABT_CommunicationProtocol::MessageType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ABT_CommunicationProtocol_AgentIdentity::kIdFieldNumber;
const int ABT_CommunicationProtocol_AgentIdentity::kHostFieldNumber;
const int ABT_CommunicationProtocol_AgentIdentity::kPortFieldNumber;
#endif  // !_MSC_VER

ABT_CommunicationProtocol_AgentIdentity::ABT_CommunicationProtocol_AgentIdentity()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_CommunicationProtocol_AgentIdentity::InitAsDefaultInstance() {
}

ABT_CommunicationProtocol_AgentIdentity::ABT_CommunicationProtocol_AgentIdentity(const ABT_CommunicationProtocol_AgentIdentity& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_CommunicationProtocol_AgentIdentity::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  host_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  port_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_CommunicationProtocol_AgentIdentity::~ABT_CommunicationProtocol_AgentIdentity() {
  SharedDtor();
}

void ABT_CommunicationProtocol_AgentIdentity::SharedDtor() {
  if (host_ != &::google::protobuf::internal::kEmptyString) {
    delete host_;
  }
  if (this != default_instance_) {
  }
}

void ABT_CommunicationProtocol_AgentIdentity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_CommunicationProtocol_AgentIdentity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_CommunicationProtocol_AgentIdentity_descriptor_;
}

const ABT_CommunicationProtocol_AgentIdentity& ABT_CommunicationProtocol_AgentIdentity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_CommunicationProtocol_AgentIdentity* ABT_CommunicationProtocol_AgentIdentity::default_instance_ = NULL;

ABT_CommunicationProtocol_AgentIdentity* ABT_CommunicationProtocol_AgentIdentity::New() const {
  return new ABT_CommunicationProtocol_AgentIdentity;
}

void ABT_CommunicationProtocol_AgentIdentity::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    if (has_host()) {
      if (host_ != &::google::protobuf::internal::kEmptyString) {
        host_->clear();
      }
    }
    port_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_CommunicationProtocol_AgentIdentity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_host;
        break;
      }

      // required string host = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_host:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_host()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->host().data(), this->host().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_port;
        break;
      }

      // required int32 port = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_CommunicationProtocol_AgentIdentity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required string host = 2;
  if (has_host()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->host().data(), this->host().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->host(), output);
  }

  // required int32 port = 3;
  if (has_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->port(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_CommunicationProtocol_AgentIdentity::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required string host = 2;
  if (has_host()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->host().data(), this->host().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->host(), target);
  }

  // required int32 port = 3;
  if (has_port()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->port(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_CommunicationProtocol_AgentIdentity::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string host = 2;
    if (has_host()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->host());
    }

    // required int32 port = 3;
    if (has_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->port());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_CommunicationProtocol_AgentIdentity::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_CommunicationProtocol_AgentIdentity* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_CommunicationProtocol_AgentIdentity*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_CommunicationProtocol_AgentIdentity::MergeFrom(const ABT_CommunicationProtocol_AgentIdentity& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_host()) {
      set_host(from.host());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_CommunicationProtocol_AgentIdentity::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_CommunicationProtocol_AgentIdentity::CopyFrom(const ABT_CommunicationProtocol_AgentIdentity& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_CommunicationProtocol_AgentIdentity::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void ABT_CommunicationProtocol_AgentIdentity::Swap(ABT_CommunicationProtocol_AgentIdentity* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(host_, other->host_);
    std::swap(port_, other->port_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_CommunicationProtocol_AgentIdentity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_CommunicationProtocol_AgentIdentity_descriptor_;
  metadata.reflection = ABT_CommunicationProtocol_AgentIdentity_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ABT_CommunicationProtocol::kTypeFieldNumber;
const int ABT_CommunicationProtocol::kIdentityFieldNumber;
const int ABT_CommunicationProtocol::kOthersFieldNumber;
#endif  // !_MSC_VER

ABT_CommunicationProtocol::ABT_CommunicationProtocol()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_CommunicationProtocol::InitAsDefaultInstance() {
  identity_ = const_cast< ::ABT_CommunicationProtocol_AgentIdentity*>(&::ABT_CommunicationProtocol_AgentIdentity::default_instance());
}

ABT_CommunicationProtocol::ABT_CommunicationProtocol(const ABT_CommunicationProtocol& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_CommunicationProtocol::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  identity_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_CommunicationProtocol::~ABT_CommunicationProtocol() {
  SharedDtor();
}

void ABT_CommunicationProtocol::SharedDtor() {
  if (this != default_instance_) {
    delete identity_;
  }
}

void ABT_CommunicationProtocol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_CommunicationProtocol::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_CommunicationProtocol_descriptor_;
}

const ABT_CommunicationProtocol& ABT_CommunicationProtocol::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_CommunicationProtocol* ABT_CommunicationProtocol::default_instance_ = NULL;

ABT_CommunicationProtocol* ABT_CommunicationProtocol::New() const {
  return new ABT_CommunicationProtocol;
}

void ABT_CommunicationProtocol::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_identity()) {
      if (identity_ != NULL) identity_->::ABT_CommunicationProtocol_AgentIdentity::Clear();
    }
  }
  others_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_CommunicationProtocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ABT_CommunicationProtocol.MessageType type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ABT_CommunicationProtocol_MessageType_IsValid(value)) {
            set_type(static_cast< ::ABT_CommunicationProtocol_MessageType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_identity;
        break;
      }

      // optional .ABT_CommunicationProtocol.AgentIdentity identity = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_identity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_identity()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_others;
        break;
      }

      // repeated .ABT_CommunicationProtocol.AgentIdentity others = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_others:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_others()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_others;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_CommunicationProtocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ABT_CommunicationProtocol.MessageType type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional .ABT_CommunicationProtocol.AgentIdentity identity = 2;
  if (has_identity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->identity(), output);
  }

  // repeated .ABT_CommunicationProtocol.AgentIdentity others = 3;
  for (int i = 0; i < this->others_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->others(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_CommunicationProtocol::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ABT_CommunicationProtocol.MessageType type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional .ABT_CommunicationProtocol.AgentIdentity identity = 2;
  if (has_identity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->identity(), target);
  }

  // repeated .ABT_CommunicationProtocol.AgentIdentity others = 3;
  for (int i = 0; i < this->others_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->others(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_CommunicationProtocol::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ABT_CommunicationProtocol.MessageType type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional .ABT_CommunicationProtocol.AgentIdentity identity = 2;
    if (has_identity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->identity());
    }

  }
  // repeated .ABT_CommunicationProtocol.AgentIdentity others = 3;
  total_size += 1 * this->others_size();
  for (int i = 0; i < this->others_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->others(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_CommunicationProtocol::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_CommunicationProtocol* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_CommunicationProtocol*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_CommunicationProtocol::MergeFrom(const ABT_CommunicationProtocol& from) {
  GOOGLE_CHECK_NE(&from, this);
  others_.MergeFrom(from.others_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_identity()) {
      mutable_identity()->::ABT_CommunicationProtocol_AgentIdentity::MergeFrom(from.identity());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_CommunicationProtocol::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_CommunicationProtocol::CopyFrom(const ABT_CommunicationProtocol& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_CommunicationProtocol::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_identity()) {
    if (!this->identity().IsInitialized()) return false;
  }
  for (int i = 0; i < others_size(); i++) {
    if (!this->others(i).IsInitialized()) return false;
  }
  return true;
}

void ABT_CommunicationProtocol::Swap(ABT_CommunicationProtocol* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(identity_, other->identity_);
    others_.Swap(&other->others_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_CommunicationProtocol::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_CommunicationProtocol_descriptor_;
  metadata.reflection = ABT_CommunicationProtocol_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ABT_Assignment::kIdFieldNumber;
const int ABT_Assignment::kValueFieldNumber;
#endif  // !_MSC_VER

ABT_Assignment::ABT_Assignment()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_Assignment::InitAsDefaultInstance() {
}

ABT_Assignment::ABT_Assignment(const ABT_Assignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_Assignment::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_Assignment::~ABT_Assignment() {
  SharedDtor();
}

void ABT_Assignment::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ABT_Assignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_Assignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_Assignment_descriptor_;
}

const ABT_Assignment& ABT_Assignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_Assignment* ABT_Assignment::default_instance_ = NULL;

ABT_Assignment* ABT_Assignment::New() const {
  return new ABT_Assignment;
}

void ABT_Assignment::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    value_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_Assignment::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_value;
        break;
      }

      // required int32 value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
          set_has_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_Assignment::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required int32 value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_Assignment::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required int32 value = 2;
  if (has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_Assignment::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required int32 value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_Assignment::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_Assignment* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_Assignment*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_Assignment::MergeFrom(const ABT_Assignment& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_Assignment::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_Assignment::CopyFrom(const ABT_Assignment& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_Assignment::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void ABT_Assignment::Swap(ABT_Assignment* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_Assignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_Assignment_descriptor_;
  metadata.reflection = ABT_Assignment_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ABT_CompoundAssignment::kAssignmentsFieldNumber;
#endif  // !_MSC_VER

ABT_CompoundAssignment::ABT_CompoundAssignment()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_CompoundAssignment::InitAsDefaultInstance() {
}

ABT_CompoundAssignment::ABT_CompoundAssignment(const ABT_CompoundAssignment& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_CompoundAssignment::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_CompoundAssignment::~ABT_CompoundAssignment() {
  SharedDtor();
}

void ABT_CompoundAssignment::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ABT_CompoundAssignment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_CompoundAssignment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_CompoundAssignment_descriptor_;
}

const ABT_CompoundAssignment& ABT_CompoundAssignment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_CompoundAssignment* ABT_CompoundAssignment::default_instance_ = NULL;

ABT_CompoundAssignment* ABT_CompoundAssignment::New() const {
  return new ABT_CompoundAssignment;
}

void ABT_CompoundAssignment::Clear() {
  assignments_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_CompoundAssignment::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ABT_Assignment assignments = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_assignments:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_assignments()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_assignments;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_CompoundAssignment::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .ABT_Assignment assignments = 1;
  for (int i = 0; i < this->assignments_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->assignments(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_CompoundAssignment::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .ABT_Assignment assignments = 1;
  for (int i = 0; i < this->assignments_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->assignments(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_CompoundAssignment::ByteSize() const {
  int total_size = 0;

  // repeated .ABT_Assignment assignments = 1;
  total_size += 1 * this->assignments_size();
  for (int i = 0; i < this->assignments_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->assignments(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_CompoundAssignment::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_CompoundAssignment* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_CompoundAssignment*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_CompoundAssignment::MergeFrom(const ABT_CompoundAssignment& from) {
  GOOGLE_CHECK_NE(&from, this);
  assignments_.MergeFrom(from.assignments_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_CompoundAssignment::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_CompoundAssignment::CopyFrom(const ABT_CompoundAssignment& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_CompoundAssignment::IsInitialized() const {

  for (int i = 0; i < assignments_size(); i++) {
    if (!this->assignments(i).IsInitialized()) return false;
  }
  return true;
}

void ABT_CompoundAssignment::Swap(ABT_CompoundAssignment* other) {
  if (other != this) {
    assignments_.Swap(&other->assignments_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_CompoundAssignment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_CompoundAssignment_descriptor_;
  metadata.reflection = ABT_CompoundAssignment_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* ABT_Message_MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_Message_MessageType_descriptor_;
}
bool ABT_Message_MessageType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ABT_Message_MessageType ABT_Message::T_OK;
const ABT_Message_MessageType ABT_Message::T_NOGOOD;
const ABT_Message_MessageType ABT_Message::T_ADDLINK;
const ABT_Message_MessageType ABT_Message::T_STOP;
const ABT_Message_MessageType ABT_Message::MessageType_MIN;
const ABT_Message_MessageType ABT_Message::MessageType_MAX;
const int ABT_Message::MessageType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ABT_Message_OK::kAssignmentFieldNumber;
#endif  // !_MSC_VER

ABT_Message_OK::ABT_Message_OK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_Message_OK::InitAsDefaultInstance() {
  assignment_ = const_cast< ::ABT_Assignment*>(&::ABT_Assignment::default_instance());
}

ABT_Message_OK::ABT_Message_OK(const ABT_Message_OK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_Message_OK::SharedCtor() {
  _cached_size_ = 0;
  assignment_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_Message_OK::~ABT_Message_OK() {
  SharedDtor();
}

void ABT_Message_OK::SharedDtor() {
  if (this != default_instance_) {
    delete assignment_;
  }
}

void ABT_Message_OK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_Message_OK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_Message_OK_descriptor_;
}

const ABT_Message_OK& ABT_Message_OK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_Message_OK* ABT_Message_OK::default_instance_ = NULL;

ABT_Message_OK* ABT_Message_OK::New() const {
  return new ABT_Message_OK;
}

void ABT_Message_OK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_assignment()) {
      if (assignment_ != NULL) assignment_->::ABT_Assignment::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_Message_OK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ABT_Assignment assignment = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_assignment()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_Message_OK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ABT_Assignment assignment = 1;
  if (has_assignment()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->assignment(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_Message_OK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ABT_Assignment assignment = 1;
  if (has_assignment()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->assignment(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_Message_OK::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ABT_Assignment assignment = 1;
    if (has_assignment()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->assignment());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_Message_OK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_Message_OK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_Message_OK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_Message_OK::MergeFrom(const ABT_Message_OK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_assignment()) {
      mutable_assignment()->::ABT_Assignment::MergeFrom(from.assignment());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_Message_OK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_Message_OK::CopyFrom(const ABT_Message_OK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_Message_OK::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_assignment()) {
    if (!this->assignment().IsInitialized()) return false;
  }
  return true;
}

void ABT_Message_OK::Swap(ABT_Message_OK* other) {
  if (other != this) {
    std::swap(assignment_, other->assignment_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_Message_OK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_Message_OK_descriptor_;
  metadata.reflection = ABT_Message_OK_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ABT_Message_NOGOOD::kNogoodFieldNumber;
#endif  // !_MSC_VER

ABT_Message_NOGOOD::ABT_Message_NOGOOD()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_Message_NOGOOD::InitAsDefaultInstance() {
  nogood_ = const_cast< ::ABT_CompoundAssignment*>(&::ABT_CompoundAssignment::default_instance());
}

ABT_Message_NOGOOD::ABT_Message_NOGOOD(const ABT_Message_NOGOOD& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_Message_NOGOOD::SharedCtor() {
  _cached_size_ = 0;
  nogood_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_Message_NOGOOD::~ABT_Message_NOGOOD() {
  SharedDtor();
}

void ABT_Message_NOGOOD::SharedDtor() {
  if (this != default_instance_) {
    delete nogood_;
  }
}

void ABT_Message_NOGOOD::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_Message_NOGOOD::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_Message_NOGOOD_descriptor_;
}

const ABT_Message_NOGOOD& ABT_Message_NOGOOD::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_Message_NOGOOD* ABT_Message_NOGOOD::default_instance_ = NULL;

ABT_Message_NOGOOD* ABT_Message_NOGOOD::New() const {
  return new ABT_Message_NOGOOD;
}

void ABT_Message_NOGOOD::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_nogood()) {
      if (nogood_ != NULL) nogood_->::ABT_CompoundAssignment::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_Message_NOGOOD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ABT_CompoundAssignment nogood = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_nogood()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_Message_NOGOOD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ABT_CompoundAssignment nogood = 1;
  if (has_nogood()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->nogood(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_Message_NOGOOD::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ABT_CompoundAssignment nogood = 1;
  if (has_nogood()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->nogood(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_Message_NOGOOD::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ABT_CompoundAssignment nogood = 1;
    if (has_nogood()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->nogood());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_Message_NOGOOD::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_Message_NOGOOD* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_Message_NOGOOD*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_Message_NOGOOD::MergeFrom(const ABT_Message_NOGOOD& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_nogood()) {
      mutable_nogood()->::ABT_CompoundAssignment::MergeFrom(from.nogood());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_Message_NOGOOD::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_Message_NOGOOD::CopyFrom(const ABT_Message_NOGOOD& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_Message_NOGOOD::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_nogood()) {
    if (!this->nogood().IsInitialized()) return false;
  }
  return true;
}

void ABT_Message_NOGOOD::Swap(ABT_Message_NOGOOD* other) {
  if (other != this) {
    std::swap(nogood_, other->nogood_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_Message_NOGOOD::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_Message_NOGOOD_descriptor_;
  metadata.reflection = ABT_Message_NOGOOD_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ABT_Message::kTypeFieldNumber;
const int ABT_Message::kIdFieldNumber;
const int ABT_Message::kOkDataFieldNumber;
const int ABT_Message::kNogoodDataFieldNumber;
#endif  // !_MSC_VER

ABT_Message::ABT_Message()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ABT_Message::InitAsDefaultInstance() {
  ok_data_ = const_cast< ::ABT_Message_OK*>(&::ABT_Message_OK::default_instance());
  nogood_data_ = const_cast< ::ABT_Message_NOGOOD*>(&::ABT_Message_NOGOOD::default_instance());
}

ABT_Message::ABT_Message(const ABT_Message& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ABT_Message::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  id_ = 0;
  ok_data_ = NULL;
  nogood_data_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ABT_Message::~ABT_Message() {
  SharedDtor();
}

void ABT_Message::SharedDtor() {
  if (this != default_instance_) {
    delete ok_data_;
    delete nogood_data_;
  }
}

void ABT_Message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ABT_Message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ABT_Message_descriptor_;
}

const ABT_Message& ABT_Message::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocols_2eproto();
  return *default_instance_;
}

ABT_Message* ABT_Message::default_instance_ = NULL;

ABT_Message* ABT_Message::New() const {
  return new ABT_Message;
}

void ABT_Message::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    id_ = 0;
    if (has_ok_data()) {
      if (ok_data_ != NULL) ok_data_->::ABT_Message_OK::Clear();
    }
    if (has_nogood_data()) {
      if (nogood_data_ != NULL) nogood_data_->::ABT_Message_NOGOOD::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ABT_Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ABT_Message.MessageType type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ABT_Message_MessageType_IsValid(value)) {
            set_type(static_cast< ::ABT_Message_MessageType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_id;
        break;
      }

      // required int32 id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_ok_data;
        break;
      }

      // optional .ABT_Message.OK ok_data = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ok_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ok_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_nogood_data;
        break;
      }

      // optional .ABT_Message.NOGOOD nogood_data = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_nogood_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_nogood_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ABT_Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ABT_Message.MessageType type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // required int32 id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // optional .ABT_Message.OK ok_data = 3;
  if (has_ok_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->ok_data(), output);
  }

  // optional .ABT_Message.NOGOOD nogood_data = 4;
  if (has_nogood_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->nogood_data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ABT_Message::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ABT_Message.MessageType type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // required int32 id = 2;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // optional .ABT_Message.OK ok_data = 3;
  if (has_ok_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->ok_data(), target);
  }

  // optional .ABT_Message.NOGOOD nogood_data = 4;
  if (has_nogood_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->nogood_data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ABT_Message::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ABT_Message.MessageType type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // required int32 id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional .ABT_Message.OK ok_data = 3;
    if (has_ok_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ok_data());
    }

    // optional .ABT_Message.NOGOOD nogood_data = 4;
    if (has_nogood_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->nogood_data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ABT_Message::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ABT_Message* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ABT_Message*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ABT_Message::MergeFrom(const ABT_Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_ok_data()) {
      mutable_ok_data()->::ABT_Message_OK::MergeFrom(from.ok_data());
    }
    if (from.has_nogood_data()) {
      mutable_nogood_data()->::ABT_Message_NOGOOD::MergeFrom(from.nogood_data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ABT_Message::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ABT_Message::CopyFrom(const ABT_Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ABT_Message::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_ok_data()) {
    if (!this->ok_data().IsInitialized()) return false;
  }
  if (has_nogood_data()) {
    if (!this->nogood_data().IsInitialized()) return false;
  }
  return true;
}

void ABT_Message::Swap(ABT_Message* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(id_, other->id_);
    std::swap(ok_data_, other->ok_data_);
    std::swap(nogood_data_, other->nogood_data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ABT_Message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ABT_Message_descriptor_;
  metadata.reflection = ABT_Message_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
